### PR TITLE
chore: add version.json with v2 bump

### PR DESCRIPTION
**Pull request by rvagg**

### CODE REVIEW

**Comment by rvagg** [comment]
hm, this isn't working right, might need the version.json file in place first or at least get web3-bot access in here; converting to draft for now

**Review by ribasushi — APPROVED** [review]
@rvagg please make absolutely sure https://github.com/filecoin-project/go-commp-utils/pull/16 makes it in before cutting 2.0 🫣

**Comment by rvagg** [comment]
Releaser needed an existing version.json to work with, so I put one in master that matches the current tagged version. But, it's having some trouble with the changes I've pushed here but I believe we're good to go now even though the last update in here has complaints.

One more look please @ribasushi? I've bumped `module` in go.mod and all uses of this package in the internal source files to `/v2`.

**Review by ribasushi — APPROVED** [review]
✅ 
```
CGO_ENABLED=0 go test -count=1 ./...
ok  	github.com/filecoin-project/go-commp-utils/v2	0.115s
ok  	github.com/filecoin-project/go-commp-utils/v2/writer	0.602s
ok  	github.com/filecoin-project/go-commp-utils/v2/zerocomm	0.196s
```

If you want to be super-thorough - [there's stale stuff here](https://github.com/filecoin-project/go-commp-utils/blob/afebbaed4/.gitignore). But it really doesn't matter.

:shipit:

**Comment by rvagg** [comment]
removed

**Comment by rvagg** [comment]
Did a thorough dep update and added a dependabot config which we're doing elsewhere too

**Pull request merged**
